version: "3.4"

services:
  miservicio_mysql:
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      target: mimysqlcom
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8181:8080

  miservicio_php:
    build:
      context: .
      target: miapachephpcom
    volumes:
      - .:/var/www/html
    links:
      - miservicio_mysql:elalias
    ports:
          - 80:80

volumes:
  mysql-db-data: