version: "3"

services:
  miservicio_mysql:
    image: mimysql
  miservicio_php:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - /home/pmorales/PhpstormProjects:/var/www/html
    expose:
      - 80
    ports:
      - 8080:80
    links:
      - miservicio_mysql